"use client";

import { InsightResponse } from "@/types/insight";

interface Props {
  insight: InsightResponse | null;
  loading: boolean;
}

export default function InsightPanel({ insight, loading }: Props) {
  if (loading) {
    return (
      <div className="bg-white rounded-xl p-6 shadow">
        Generating AI insight...
      </div>
    );
  }

  if (!insight) {
    return (
      <div className="bg-white rounded-xl p-6 shadow">
        AI insight not available.
      </div>
    );
  }

  function getPriorityColor(priority: string) {
    if (priority === "HIGH") {
      return "bg-red-100 border-red-300";
    }

    if (priority === "MEDIUM") {
      return "bg-yellow-100 border-yellow-300";
    }

    return "bg-green-100 border-green-300";
  }

  function getInsightIcon(type: string) {
    if (type === "warning") {
      return "⚠️";
    }

    if (type === "opportunity") {
      return "📈";
    }

    return "✅";
  }

  return (
    <div className="bg-white rounded-xl p-6 shadow space-y-6">
      {/* HEADER */}
      <div>
        <h2 className="text-2xl font-bold">🤖 AI Business Insight</h2>

        <p className="text-gray-500 text-sm mt-1">
          Generated by NusantaraInsight AI
        </p>
      </div>

      {/* HEALTH SCORE */}
      <div className="bg-gray-100 rounded-xl p-4">
        <p className="text-sm text-gray-500">Product Health Score</p>

        <h3 className="text-4xl font-bold mt-2">{insight.health_score}/100</h3>
      </div>

      {/* SUMMARY */}
      <div>
        <h3 className="font-semibold mb-2">AI Summary</h3>

        <p className="text-gray-700 leading-relaxed">{insight.summary}</p>
      </div>

      {/* INSIGHTS */}
      <div className="space-y-3">
        <h3 className="font-semibold">Insights</h3>

        {insight.insights.map((item, index) => (
          <div
            key={index}
            className={`
              border rounded-xl p-4
              ${getPriorityColor(item.priority)}
            `}
          >
            <div className="flex items-center justify-between">
              <h4 className="font-bold flex items-center gap-2">
                <span>{getInsightIcon(item.type)}</span>

                {item.title}
              </h4>

              <span className="text-sm font-medium">{item.priority}</span>
            </div>

            <p className="text-gray-700 mt-2">{item.description}</p>
          </div>
        ))}
      </div>

      {/* RECOMMENDATIONS */}
      <div>
        <h3 className="font-semibold mb-2">Recommendations</h3>

        <ul className="space-y-2">
          {insight.recommendations.map((rec, index) => (
            <li key={index} className="bg-blue-50 p-3 rounded-lg">
              💡 {rec}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
